# Generated by Django 4.0.3 on 2022-12-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binvo',
            name='bin_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
