# Generated by Django 4.0.3 on 2022-12-05 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_binvo_bin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='bin_id',
        ),
    ]
